name: CI-CD

on:
  push:
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: action/checkout@v3
    - name: Configuracao node
      uses: actions/setup-node@v3
      with:
        node-version: '18.10'
        cache: 'npm'
    - run: npm install
    - run: npm run build